version: "3.9"

services:
  backend:
    build:
      context: .
      target: production
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

